config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  resources :menus
  resources :orders
  resources :customers

  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :first_name, presence: true
  validates :email, presence: true
  validates :password, length: { in: 6..20 }
  has_secure_password
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  def self.starter
    all.where("dish_type=?", "Starter")
  end

  def self.cooldrink
    all.where("dish_type=?", "Drinks")
  end
  def self.fruitjuice
    all.where("dish_type=?", "Fruit Juice")
  end

  def self.chinese
    all.where("dish_type=?", "Chinese")
  end

  def self.meals
    all.where("dish_type=?", "Meals")
  end

  def self.others
    all.where("dish_type=?", "Others")
  end

  def self.Veg
    all.where("item_type=?", "Veg")
  end

  def self.Nonveg
    all.where("item_type=?", "Non-Veg")
  end

  def self.Others
    all.where("item_type=?", "Others")
  end

  def menu_display
    "#{item} #{price} #{item_type} #{dish_type}"
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  def order_display
    "#{id}.  #{billamount}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    #Memoization
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = Customer.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "customers/new"
  end

  def create
    customer = Customer.find_by(email: params[:email])
    if customer
      flash[:error] = "User with entered details exists.Please try again."
      redirect_to new_customer_path
    else
      new_customer = Customer.new(
        first_name: params[:first_name],
        last_name: params[:last_name],
        email: params[:email],
        password: params[:password],
      )
      if new_customer.save
        redirect_to "/"
      else
        flash[:error] = new_customer.errors.full_messages.join(",")
        redirect_to new_customer_path
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to menus_path
    else
      render "index"
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    if current_user.email == "harshasyam2@gmail.com"
      render "index", locals: { show_adding_column: true, show_delete: true }
    else
      render "index", locals: { show_adding_column: false, show_delete: false }
    end
  end

  def create
    Menu.create!(
      item: params[:item],
      price: params[:price],
      item_type: params[:item_type],
      dish_type: params[:dish_type],
      extension: params[:extension],
    )
    redirect_to menus_path
  end

  def destroy
    id = params[:id]
    menu = Menu.find(id)
    menu.destroy
    redirect_to menus_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    render plain: Order.all.map { |order| order.order_display }.join("\n")
  end

  def change
    totalitems = params[:totalitems]
    billvalue = totalitems * 100
    new_order = Order.create!(billamount: billvalue)
    render plain: new_order.order_display
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "new"
  end

  def create
    customer = Customer.find_by(email: params[:email])
    if customer && customer.authenticate(params[:password])
      session[:current_user_id] = customer.id
      redirect_to "/"
    else
      flash[:error] = "Invalid username or password.Please retry"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user_id = nil
    redirect_to "/"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/new.html.erb
<div class="Customer_signup">
  <h1 class="NewCustomers_title">Welcome new Customer!</h1>
  <section class="NewCustomers">
    <%= form_with url:customers_path do |form| %>
      <div class="Form-section">
        <div class="Form-input-label">First Name:<p class="Mandatory"> * </p></div>
        <%= form.text_field :first_name,class:"Form-input" %>
      </div>
      <div class="Form-section">
        <div class="Form-input-label">Last Name:</div>
        <%= form.text_field :last_name,class:"Form-input" %>
      </div>
      <div class="Form-section">
        <div class="Form-input-label">Email:<p class="Mandatory"> * </p></div>
        <%= form.email_field :email,class:"Form-input" %>
      </div>
      <div class="Form-section">
        <div class="Form-input-label">Password:<p class="Mandatory"> * </p></div>
        <%= form.password_field :password,class:"Form-input"  %>
      </div>
      <div class="Form-section">
        <%= form.submit "Sign Up",class:"Form-submit"%>
      </div>
    <% end %>
  </section>
</div>

app/views/home/index.html.erb
<section class="Home_page_menu">
  <div class="Home_creation_line">
    <p class="Home_menu create" ><%= link_to "Create Account", new_customer_path %></p>
    <p class="Home_menu signin" ><%= link_to "Sign in",new_sessions_path %></p>
  </div>
    <h1 class="heading">Welcome to our restaurent!</h1>
    <p class="content"> <img src="content.png"></p>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafeteria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <p class="Customer_heading">
        Welcome <%= @current_user.first_name %>!
        <%= link_to "Sign out", destroy_session_path, method:"delete"%>
      </p>
    <% end %>
      <p class="Flash-error"> <%= flash[:error] %> </p>
        <%= yield %>
  </body>
</html>

app/views/menus/_menu-section.html.erb
  <table class="Menu_display" width="100%">
  <p class="title"><%= menu_title %></p>
  <% menus.all.each do |menu|%>
        <tr>
          <td>
            <img class="image" src="<%=menu.item%>.<%=menu.extension%>" width="50%">
          </td>
          <td>
            <p class="display_price">
              Price :<%=menu.price%>/-
            </p>
          </td>
          <td>
           <input class="item_count" type="number" min="0" max="1000">
          </td>
          <% if show_delete_btn %>
            <%= form_with(url: "/menus/#{menu.id}",method: "DELETE") do %>
              <td>
                <input class="delete" type="submit" value="Remove Item">
              </td>
            <% end %>
          <% end %>
        </tr>

      <tr>
          <th>
           <p class="Menu_name"> <%=menu.item %></p>
          </th>
      </tr>
  <% end %>
  </table>

app/views/menus/index.html.erb
<main class="Main_page">
  <section class="cart" >
    <img src="cart.png" width="40%">
  </section>

  <% if show_adding_column %>
    <form class="Add_menu" action="/menus" method="POST">
        <input class="item" type="text" name="item" size="15" placeholder="Add an item">
        <input class="price" type="text" name="price" size="10" placeholder="Enter Price">
        <input class="item_type" type="text" name="item_type" size="13" placeholder="Item Type">
        <input class="dish_type" type="text" name="dish_type" size="15" placeholder="Dish Type">
        <input class="extension" type="text" name="extension" size="10" placeholder="Extension Format">
        <input class="submit" type="submit" value="Add an item">
    </form>
  <% end %>

  <p class="Menu-title">Vegeterian Menu</p>
  <hr>
  <%= render partial: "menu-section", locals: {menu_title:"Veg Starters",menus:Menu.Veg.starter,show_delete_btn:show_delete}%>
  <%= render partial: "menu-section", locals: {menu_title:"Veg Chinese",menus:Menu.Veg.chinese,show_delete_btn:show_delete}%>
  <%= render partial: "menu-section", locals: {menu_title:"Veg Meals",menus:Menu.Veg.meals,show_delete_btn:show_delete}%>
  <%= render partial: "menu-section", locals: {menu_title:"Veg Others",menus:Menu.Veg.others,show_delete_btn:show_delete}%>

  <p class="Menu-title">Non Vegeterian Menu</p>
  <hr>
  <%= render partial: "menu-section", locals: {menu_title:"Non-Veg Starters",menus:Menu.Nonveg.starter,show_delete_btn:show_delete}%>
  <%= render partial: "menu-section", locals: {menu_title:"Non-Veg Chinese",menus:Menu.Nonveg.chinese,show_delete_btn:show_delete}%>
  <%= render partial: "menu-section", locals: {menu_title:"Non-Veg Meals",menus:Menu.Nonveg.meals,show_delete_btn:show_delete}%>
  <%= render partial: "menu-section", locals: {menu_title:"Non-Veg Others",menus:Menu.Nonveg.others,show_delete_btn:show_delete}%>
  <p class="Menu-title">Drinks</p>

  <hr>
  <%= render partial: "menu-section", locals: {menu_title:"Cool Drinks",menus:Menu.Others.cooldrink,show_delete_btn:show_delete}%>
  <%= render partial: "menu-section", locals: {menu_title:"Fruit Juice",menus:Menu.Others.fruitjuice,show_delete_btn:show_delete}%>
</main>

app/views/orders/index.html.erb
<p>Hello Orders</p>